apiVersion: v1
kind: Service
metadata:
  name: gluetun
  labels: { { - include "gluetun.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: 9999
      targetPort: health
      protocol: TCP
      name: health
  selector: { { - include "gluetun.selectorLabels" . | nindent 4 } }
