apiVersion: v1
kind: Service
metadata:
  name: { { include "gluetun.fullname" . } }
  labels: { { - include "gluetun.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.proxyPort } }
      targetPort: proxy
      protocol: TCP
      name: proxy
    # - port: {{ .Values.service.healthPort }}
    #   targetPort: health
    #   protocol: TCP
    #   name: health
  selector: { { - include "gluetun.selectorLabels" . | nindent 4 } }
